### PR TITLE
Add new lines spanish

### PR DESCRIPTION
**Pull request by yako1984**

### CODE REVIEW

**Comment by hartenthaler** [comment]
Thank you!

Is this correct?
```
Consuegros
Hermann tiene 2 Consuegra y 1 Consuegra registrada (3 en total).
```

In the part "Partner chains" there are items that are not translated:
```
Partnerketten
Hermann tiene 1 Cónyuge y 2 Partnerinnen in dieser Partnerkette registrados (3 en total).
Es gibt 2 Zweige in der Partnerkette. Der längste Zweig in der Partnerkette zu Dieter Manfred Gleichfeld (I9548) besteht aus 3 Partnern (einschließlich Hermann).
```

**Comment by yako1984** [comment]
> Thank you!
> 
> Is this correct?
> 
> ```
> Consuegros
> Hermann tiene 2 Consuegra y 1 Consuegra registrada (3 en total).
> ```
> 
> In the part "Partner chains" there are items that are not translated:
> 
> ```
> Partnerketten
> Hermann tiene 1 Cónyuge y 2 Partnerinnen in dieser Partnerkette registrados (3 en total).
> Es gibt 2 Zweige in der Partnerkette. Der längste Zweig in der Partnerkette zu Dieter Manfred Gleichfeld (I9548) besteht aus 3 Partnern (einschließlich Hermann).
> ```

Bug

**Comment by yako1984** [comment]
> Partnerketten


This I do not know what it means, I left it pending while I investigate what it is.

**Comment by yako1984** [comment]
Partnerketten
Hermann tiene 1 Cónyuge y 2 Partnerinnen in dieser Partnerkette registrados (3 en total).
Es gibt 2 Zweige in der Partnerkette. 

You can send me a screenshot of this section on your website, to be able to see the context, and to be able to translate it, thank you.

**Comment by hartenthaler** [comment]
The second screenshot in the [README](https://github.com/hartenthaler/hh_extended_family) shows this element.

A partner chain is a chain (better tree) of partners of partners of partners ...

**Pull request merged**
